# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 287d82e38bdd45a67ad972b93a1265d436fbffa28829267ef6854a7e6e1c1b70d83ab48d8110989df7c38d9ec82567123a16f54f97e3464e0d675d63126a14dc

test:
  secret_key_base: 4b5afe18b84fa0d04bd6f372b34eacdff48170a0c6f6acbadca24afe3fa266aa1eedf025ef17d49b33e28358f2ffc5c8af61fe348871c7a815e96cadb29ede16

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
